apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-db-secret
  labels:
    app: {{ include "ecommerce.fullname" . | default .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretsData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}