apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . | default .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ecommerce.fullname" . | default .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}